# I like scons cuz it's Python ;-)
#
CCFLAGS = ['-Wall', '-pedantic']

if ARGUMENTS.get('debug', 0):
    CCFLAGS.append('-g')

envcpp = Environment(
            CCFLAGS=CCFLAGS,
            CPPPATH=['.'],
        )

# All C++ files 
#
cppfiles = Glob('src/*.cpp')

envcpp.Program(target='barevm', source=cppfiles)


